/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'secondary-fixed-dim': '#96d2cb',
        'inverse-on-surface': '#cbfdd0',
        'surface-bright': '#eaffe9',
        'on-error-container': '#93000a',
        'primary-fixed-dim': '#b1cbd1',
        'tertiary-fixed-dim': '#82d8ae',
        'outline-variant': '#c2c7c9',
        'on-tertiary-fixed': '#002114',
        'surface-container-low': '#d2ffd6',
        'on-error': '#ffffff',
        'on-surface-variant': '#424849',
        primary: '#00090c',
        error: '#ba1a1a',
        'tertiary-fixed': '#9df4c9',
        'on-secondary': '#ffffff',
        'tertiary-container': '#002517',
        'on-secondary-fixed': '#00201e',
        secondary: '#2b6862',
        'on-secondary-fixed-variant': '#0a504b',
        'primary-fixed': '#cde7ee',
        'secondary-fixed': '#b1eee7',
        'error-container': '#ffdad6',
        'surface-dim': '#b4e6ba',
        'on-primary-fixed': '#051f24',
        'primary-container': '#092328',
        'on-primary-container': '#728b91',
        'inverse-primary': '#b1cbd1',
        'on-background': '#00210b',
        background: '#eaffe9',
        'secondary-container': '#b1eee7',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#409671',
        'on-primary': '#ffffff',
        'surface-tint': '#4a6268',
        surface: '#eaffe9',
        'surface-container-high': '#c2f5c8',
        'on-primary-fixed-variant': '#324b50',
        'on-secondary-container': '#326e68',
        tertiary: '#000904',
        'surface-container-lowest': '#ffffff',
        'surface-variant': '#bdefc3',
        'inverse-surface': '#09381a',
        'on-tertiary-fixed-variant': '#005237',
        'on-surface': '#00210b',
        'surface-container-highest': '#bdefc3',
        outline: '#72787a',
        'surface-container': '#c8face',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'space-lg': '1.5rem',
        'space-sm': '0.5rem',
        'gutter-mobile': '1rem',
        gutter: '1.5rem',
        margin: '3rem',
        'space-xl': '2.5rem',
        'space-md': '1rem',
        'margin-mobile': '1.25rem',
        'space-xs': '0.25rem',
      },
      fontFamily: {
        'label-sm': ['Plus Jakarta Sans'],
        'label-lg': ['Plus Jakarta Sans'],
        title: ['Plus Jakarta Sans'],
        display: ['Plus Jakarta Sans'],
        'body-sm': ['Inter'],
        'headline-lg': ['Plus Jakarta Sans'],
        'body-lg': ['Inter'],
        'headline-lg-mobile': ['Plus Jakarta Sans'],
        'headline-md': ['Plus Jakarta Sans'],
        'body-md': ['Inter'],
        'headline-sm': ['Plus Jakarta Sans'],
        'display-mobile': ['Plus Jakarta Sans'],
        'label-md': ['Plus Jakarta Sans'],
      },
      fontSize: {
        'label-sm': ['11px', { lineHeight: '14px', letterSpacing: '0.04em', fontWeight: '700' }],
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        title: ['18px', { lineHeight: '26px', fontWeight: '600' }],
        display: ['56px', { lineHeight: '64px', letterSpacing: '-0.03em', fontWeight: '800' }],
        'body-sm': ['13px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', letterSpacing: '-0.015em', fontWeight: '700' }],
        'body-md': ['15px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-sm': ['22px', { lineHeight: '30px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-mobile': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.03em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
